/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.vitorrural.lp_trabalho;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 *
 * @author USUARIO
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
     private TipoFerramenta ferramentaAtual = TipoFerramenta.CIRCULO;

    // variáveis para arrastar e formar figuras
    private int startX, startY, endX, endY;
    public NewJFrame() {
        initComponents();
        configurarEventosDeDesenho();
        Painel_de_Desenho.setBackground(Color.WHITE);
    }
    private void configurarEventosDeDesenho() {

        Painel_de_Desenho.addMouseListener(new MouseAdapter() {

            @Override
            public void mousePressed(MouseEvent e) {
                startX = e.getX();
                startY = e.getY();

                // Spray é imediato no clique
                if (ferramentaAtual == TipoFerramenta.SPRAY) {
                    aplicarSpray(e.getX(), e.getY());
                }
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                endX = e.getX();
                endY = e.getY();

                if (ferramentaAtual == TipoFerramenta.RETANGULO) {
                desenharRetangulo();
        }
}

        });

        Painel_de_Desenho.addMouseMotionListener(new MouseAdapter() {

            @Override
            
public void mouseDragged(MouseEvent e) {
    endX = e.getX();
    endY = e.getY();

    switch (ferramentaAtual) {
        case BORRACHA:
            apagarPonto(endX, endY);
            break;

        case SPRAY:
            aplicarSpray(endX, endY);
            break;

        case CIRCULO:
            desenharCirculoArrasto(endX, endY);
            break;

        case RETANGULO:
            break;

        default:
            break;
    }
}

        });

    }
    private void desenharCirculoArrasto(int x, int y) {
    Graphics g = Painel_de_Desenho.getGraphics();
    try {
        g.setColor(Selecao_de_Cor.getColor());
        int raio = 20; // ajuste o tamanho aqui se quiser
        int diametro = raio * 2;
        g.fillOval(x - raio, y - raio, diametro, diametro);
    } finally {
        g.dispose();
    }
}
private void desenharRetanguloArrasto(int x, int y) {
    Graphics g = Painel_de_Desenho.getGraphics();
    try {
        g.setColor(Selecao_de_Cor.getColor());
        int largura = 30; // ajuste largura
        int altura  = 20; // ajuste altura
        g.fillRect(x - largura/2, y - altura/2, largura, altura);
    } finally {
        g.dispose();
    }
}

    private void desenharCirculo(Graphics2D g2, Point ponto) {
    int raio = 20; // tamanho fixo do círculo (altere se quiser)
    int diametro = raio * 2;

    g2.fillOval(ponto.x - raio, ponto.y - raio, diametro, diametro);
}

    private void desenharRetangulo() {
    Graphics g = Painel_de_Desenho.getGraphics();
    g.setColor(Selecao_de_Cor.getColor());

    int x = Math.min(startX, endX);
    int y = Math.min(startY, endY);
    int width = Math.abs(endX - startX);
    int height = Math.abs(endY - startY);

    g.fillRect(x, y, width, height);
}

    private void aplicarSpray(int x, int y) {
        Graphics g = Painel_de_Desenho.getGraphics();
        g.setColor(Selecao_de_Cor.getColor());

        int raio = 20;

        for (int i = 0; i < 50; i++) {
            int dx = (int) (Math.random() * raio * 2 - raio);
            int dy = (int) (Math.random() * raio * 2 - raio);

            if (dx * dx + dy * dy <= raio * raio) {
                g.fillOval(x + dx, y + dy, 3, 3);
            }
        }
    }

    private void apagarPonto(int x, int y) {
        Graphics g = Painel_de_Desenho.getGraphics();
        g.setColor(Color.WHITE);
        g.fillRect(x - 10, y - 10, 20, 20);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_de_Desenho = new javax.swing.JPanel();
        Selecao_de_Cor = new javax.swing.JColorChooser();
        btn_Circulo = new javax.swing.JButton();
        btn_Retangulo = new javax.swing.JButton();
        btn_Spray = new javax.swing.JButton();
        btn_Borracha = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout Painel_de_DesenhoLayout = new javax.swing.GroupLayout(Painel_de_Desenho);
        Painel_de_Desenho.setLayout(Painel_de_DesenhoLayout);
        Painel_de_DesenhoLayout.setHorizontalGroup(
            Painel_de_DesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 758, Short.MAX_VALUE)
        );
        Painel_de_DesenhoLayout.setVerticalGroup(
            Painel_de_DesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        btn_Circulo.setText("Circulo");
        btn_Circulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CirculoActionPerformed(evt);
            }
        });

        btn_Retangulo.setText("Retangulo");
        btn_Retangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RetanguloActionPerformed(evt);
            }
        });

        btn_Spray.setText("Spray");
        btn_Spray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SprayActionPerformed(evt);
            }
        });

        btn_Borracha.setText("Borracha");
        btn_Borracha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BorrachaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Retangulo)
                    .addComponent(btn_Circulo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Spray, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Borracha, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Painel_de_Desenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Selecao_de_Cor, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Painel_de_Desenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btn_Circulo)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Retangulo)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Spray)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Borracha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)))
                .addComponent(Selecao_de_Cor, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CirculoActionPerformed
        ferramentaAtual = TipoFerramenta.CIRCULO;
    }//GEN-LAST:event_btn_CirculoActionPerformed

    private void btn_RetanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RetanguloActionPerformed
        ferramentaAtual = TipoFerramenta.RETANGULO;
    }//GEN-LAST:event_btn_RetanguloActionPerformed

    private void btn_SprayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SprayActionPerformed
        ferramentaAtual = TipoFerramenta.SPRAY;
    }//GEN-LAST:event_btn_SprayActionPerformed

    private void btn_BorrachaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BorrachaActionPerformed
        ferramentaAtual = TipoFerramenta.BORRACHA;
    }//GEN-LAST:event_btn_BorrachaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Painel_de_Desenho;
    private javax.swing.JColorChooser Selecao_de_Cor;
    private javax.swing.JButton btn_Borracha;
    private javax.swing.JButton btn_Circulo;
    private javax.swing.JButton btn_Retangulo;
    private javax.swing.JButton btn_Spray;
    // End of variables declaration//GEN-END:variables
}
